export const mockMaterials = {
    1: {
        id: 1,

        topic_id: 1,
        owner_id: 1,

        name: "Cellular Respiration Deep Dive",

        type: "studydoc",

        status: "completed",

        created_at: "2026-08-11T14:54:42Z",
        updated_at: "2026-08-11T14:54:42Z",

        content_json: {
            title: "Cellular Respiration Deep Dive",

            description:
                "Generated by NotebookAI • Tap the settings icon next to any block to interact",

            blocks: [
                {
                    id: "h1",
                    type: "heading",
                    data: {
                        text: "Glycolysis Overview",
                        level: 2,
                    },
                },

                {
                    id: "b2",
                    type: "text",
                    data: {
                        text:
                            "Glycolysis is the metabolic pathway that converts glucose into pyruvate. The free energy released in this process is used to form the high-energy molecules ATP and NADH.",
                    },
                },

                {
                    id: "b3",
                    type: "image",
                    data: {
                        url:
                            "https://cdn.savemyexams.com/uploads/2022/10/glycolysis-ib-specific.png",
                        caption:
                            "The 10 steps of Glycolysis",
                    },
                },

                {
                    id: "h2",
                    type: "heading",
                    data: {
                        text: "The Investment Phase",
                        level: 2,
                    },
                },

                {
                    id: "b4",
                    type: "text",
                    data: {
                        text:
                            "The investment phase consumes ATP to destabilize the glucose molecule and prepare it for cleavage.",
                    },
                },

                {
                    id: "q1",
                    type: "question-single",
                    data: {
                        type: "multiple-choice",
                        prompt:
                            "How many net ATP are produced during glycolysis?",
                        options: [
                            "2",
                            "4",
                            "32",
                            "36",
                        ],
                        correctIndex: 0,
                        allowReset: false,
                    },
                },

                {
                    id: "h3",
                    type: "heading",
                    data: {
                        text: "The Krebs Cycle",
                        level: 2,
                    },
                },

                {
                    id: "b5",
                    type: "text",
                    data: {
                        text:
                            "Following glycolysis, pyruvate enters the mitochondrial matrix to begin the Krebs cycle.",
                    },
                },

                {
                    id: "tbl-001",
                    type: "table",
                    data: {
                        columns: [
                            "Stage",
                            "Location",
                            "Net ATP",
                        ],

                        rows: [
                            [
                                "Glycolysis",
                                "Cytoplasm",
                                "2",
                            ],
                            [
                                "Krebs Cycle",
                                "Mitochondrial Matrix",
                                "2",
                            ],
                            [
                                "Electron Transport Chain",
                                "Inner Mitochondrial Membrane",
                                "26–28",
                            ],
                        ],

                        caption:
                            "Major stages of cellular respiration.",
                    },
                },
            ],
        },
    },

    2: {
        id: 2,
        topic_id: 1,
        owner_id: 1,

        name: "Glycolysis Notes",

        type: "studydoc",

        status: "draft",

        created_at: "2026-08-15T10:00:00Z",
        updated_at: "2026-08-20T15:30:00Z",

        content_json: {
            title: "Glycolysis Notes",
            description:
                "Notes covering the main stages of glycolysis.",

            blocks: [
                {
                    id: "h1",
                    type: "heading",
                    data: {
                        text: "Overview",
                        level: 2,
                    },
                },

                {
                    id: "b1",
                    type: "text",
                    data: {
                        text:
                            "Glycolysis occurs in the cytoplasm and converts one glucose molecule into two pyruvate molecules.",
                    },
                },
            ],
        },
    },

    3: {
        id: 3,
        topic_id: 1,
        owner_id: 1,

        name: "Cellular Respiration Presentation",

        type: "presentation",

        status: "draft",

        created_at: "2026-08-17T09:30:00Z",
        updated_at: "2026-08-21T11:00:00Z",

        content_json: {
            title:
                "Cellular Respiration Presentation",

            description:
                "Presentation covering the major stages of cellular respiration.",

            blocks: [],
        },
    },

    4: {
        id: 4,
        topic_id: 1,
        owner_id: 1,

        name: "Krebs Cycle Summary",

        type: "studydoc",

        status: "completed",

        created_at: "2026-08-18T12:00:00Z",
        updated_at: "2026-08-22T09:15:00Z",

        content_json: {
            title: "Krebs Cycle Summary",

            description:
                "A concise summary of the Krebs cycle.",

            blocks: [
                {
                    id: "h1",
                    type: "heading",
                    data: {
                        text: "The Krebs Cycle",
                        level: 2,
                    },
                },

                {
                    id: "b1",
                    type: "text",
                    data: {
                        text:
                            "The Krebs cycle generates electron carriers such as NADH and FADH2 that feed the electron transport chain.",
                    },
                },
            ],
        },
    },

    5: {
        id: 5,
        topic_id: 1,
        owner_id: 1,

        name: "Full Material Demo",

        type: "studydoc",

        status: "completed",

        created_at: "2026-08-18T12:00:00Z",
        updated_at: "2026-08-22T09:15:00Z",

        content_json: {
            title: "Full Material Demo Title",

            description: "Generated by NotebookAI • Tap the settings icon next to any block to interact",

            blocks: [
                {
                    id: "h1",
                    type: "heading",
                    data: {
                        text: "Glycolysis Overview",
                        level: 2,
                    },
                },
                {
                    id: "b2",
                    type: "text",
                    data: {
                        text: "Glycolysis is the metabolic pathway that converts glucose into pyruvate. The free energy released in this process is used to form the high-energy molecules ATP and NADH.",
                    },
                },
                {
                    id: "b3",
                    type: "image",
                    data: {
                        url: "https://cdn.savemyexams.com/uploads/2022/10/glycolysis-ib-specific.png",
                        caption: "The 10 steps of Glycolysis",
                    },
                },
                {
                    id: "h2",
                    type: "heading",
                    data: {
                        text: "The Investment Phase",
                        level: 2,
                    },
                },
                {
                    id: "b4",
                    type: "text",
                    data: {
                        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, neque quis efficitur tempus, felis est lacinia eros, eget placerat nisl risus eget libero. Aliquam ac ornare quam. Maecenas vitae risus condimentum, congue velit id, ultrices sem. Nullam vitae pharetra dui, eu interdum lectus. Suspendisse eu mauris interdum eros faucibus ullamcorper. In sapien sem, gravida ut turpis vitae, pretium blandit est. Morbi cursus massa turpis, quis viverra nisl auctor sed. Aliquam sollicitudin, sem a elementum maximus, ipsum urna aliquet arcu, a euismod tortor nunc a ante. Phasellus eleifend lorem sit amet metus lobortis varius. Nulla iaculis turpis nec purus eleifend, imperdiet imperdiet lorem pulvinar. Fusce id iaculis nibh, eu consectetur ante.",
                    },
                },
                {
                    id: "q1",
                    type: "question-single",
                    data: {
                        type: "multiple-choice",
                        prompt: "How many net ATP are produced during glycolysis?",
                        options: ["2", "4", "32", "36"],
                        correctIndex: 0,
                        allowReset: false,
                    },
                },
                {
                    id: "q2",
                    type: "question-single",
                    data: {
                        type: "free-response",
                        prompt: "Explain why the investment phase is necessary.",
                        feedbackTarget:
                            "Ensure your answer touches on the investment of 2 ATP required to destabilize the glucose molecule.",
                        allowReset: false,
                    },
                },
                {
                    id: "h3",
                    type: "heading",
                    data: {
                        text: "The Krebs Cycle",
                        level: 2,
                    },
                },
                {
                    id: "b5",
                    type: "text",
                    data: {
                        text: "Following glycolysis, the pyruvate enters the mitochondrial matrix to begin the Krebs Cycle.",
                    },
                },
                {
                    id: "seq1",
                    type: "question-sequence",
                    data: {
                        title: "Krebs Cycle Mini-Quiz",
                        viewMode: "paginated",
                        questions: [
                            {
                                id: "seq1-q1",
                                type: "multiple-choice",
                                prompt: "Where does the Krebs cycle take place?",
                                options: [
                                    "Cytoplasm",
                                    "Mitochondrial Matrix",
                                    "Inner Mitochondrial Membrane",
                                    "Nucleus",
                                ],
                                correctIndex: 1,
                            },
                            {
                                id: "seq1-q2",
                                type: "free-response",
                                prompt: "What is the main purpose of the Krebs cycle?",
                                feedbackTarget:
                                    "Focus on the generation of electron carriers (NADH and FADH2) for the electron transport chain.",
                            },
                        ],
                    },
                },
                {
                    id: "h4",
                    type: "heading",
                    data: {
                        text: "Final Assessment",
                        level: 2,
                    },
                },
                {
                    id: "b6",
                    type: "text",
                    data: {
                        text: "Let's test your overall understanding of cellular respiration.",
                    },
                },
                {
                    id: "seq2",
                    type: "question-sequence",
                    data: {
                        title: "Section Final Check",
                        viewMode: "list",
                        submitMode: "batch",
                        questions: [
                            {
                                id: "seq2-q1",
                                type: "multiple-choice",
                                prompt: "Which stage of cellular respiration produces the most ATP?",
                                options: [
                                    "Glycolysis",
                                    "Krebs Cycle",
                                    "Electron Transport Chain",
                                    "Fermentation",
                                ],
                                correctIndex: 2,
                                allowReset: false,
                            },
                            {
                                id: "seq2-q2",
                                type: "multiple-choice",
                                prompt: "Oxygen is directly required for which of the following?",
                                options: [
                                    "Glycolysis",
                                    "Electron Transport Chain",
                                    "Lactic Acid Fermentation",
                                    "Alcoholic Fermentation",
                                ],
                                correctIndex: 1,
                            },
                        ],
                    },
                },
                {
                    id: "tbl-001",
                    type: "table",
                    data: {
                        columns: ["Stage", "Location", "Net ATP"],
                        rows: [
                            ["Glycolysis", "Cytoplasm", "2"],
                            ["Krebs Cycle", "Mitochondrial Matrix", "2"],
                            ["Electron Transport Chain", "Inner Mitochondrial Membrane", "26–28"]
                        ],
                        caption: "Major stages of cellular respiration."
                    }
                },
                {
                    id: "f1",
                    type: "function-visual",
                    data: {
                        "formula": "x^2",
                        "caption": "A quadratic function",
                        "xMin": -5,
                        "xMax": 5,
                        "yMin": -2,
                        "yMax": 10
                    },
                },
                {
                    id: "shape1",
                    type: "2d-shape",
                    data: 
                    {
                        "shapeType": "rectangle",
                        "parameters": {
                            "width": 8,
                            "height": 5
                        },
                        "labels": ["A", "B", "C", "D"],
                        "caption": "A rectangle with width 8 and height 5."
                    }
                },
                {
                    id: "b7",
                    type: "text",
                    data: {
                        text: "Formula 1:",
                    },
                },
                {
                    id: "formula1",
                    type: "formula",
                    data: {
                        formula: "a^2 + b^2 = c^2",
                        displayMode: true,
                        caption: "Math Formula 1",
                    }
                },
                {
                    id: "b8",
                    type: "text",
                    data: {
                        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, neque quis efficitur tempus, felis est lacinia eros, eget placerat nisl risus eget libero. Aliquam ac ornare quam. Maecenas vitae risus condimentum, congue velit id, ultrices sem. Nullam vitae pharetra dui, eu interdum lectus. Suspendisse eu mauris interdum eros faucibus ullamcorper. In sapien sem, gravida ut turpis vitae, pretium blandit est. Morbi cursus massa turpis, quis viverra nisl auctor sed. Aliquam sollicitudin, sem a elementum maximus, ipsum urna aliquet arcu, a euismod tortor nunc a ante. Phasellus eleifend lorem sit amet metus lobortis varius. Nulla iaculis turpis nec purus eleifend, imperdiet imperdiet lorem pulvinar. Fusce id iaculis nibh, eu consectetur ante.",
                    },
                },
                {
                    id: "formula2",
                    type: "formula",
                    data: {
                        formula: "\\int_0^1 x^2\\,dx = \\frac{1}{3}",
                        displayMode: true,
                        caption: "Math Formula 2",
                    }
                },
                {
                    id: "code1",
                    type: "code",
                    data: {
                        language: "python",
                        code: "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)",
                        caption: "A simple JavaScript Hello World example."
                    }
                },
            ],
        },
    },
};